spring.application.name=BackEnd

# Database Configuration - PostgreSQL (Production)
spring.datasource.url=jdbc:postgresql://localhost:5432/elixozero
spring.datasource.username=postgres
spring.datasource.password=Chico-2019
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Configuration
server.port=8080